/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.34 from the
 * contents of XS.xs. Do not edit this file, edit XS.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "XS.xs"
#define PERL_NO_GET_CONTEXT
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"

#include "record_store.h"

  // store_fetch
  // store_delete
  // store_recycle
  // store_has_id
  // store_empty
  // store_unlink
  // store_empty_recyler
  
  // store_create_transaction
  // store_list_transactions
  // transaction_stow
  // transaction_delete
  // transaction_recycle
  // transaction_commit
  // transaction_rollback

  // silo_open
  // silo_empty
  // silo_next_id
  // silo_pop
  // silo_push
  // silo_put
  // silo_get
  // silo_unlink

#line 45 "XS.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
	    Perl_croak_nocontext("Usage: %s::%s(%s)", hvname, gvname, params);
        else
	    Perl_croak_nocontext("Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
	Perl_croak_nocontext("Usage: CODE(0x%" UVxf ")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#define croak_xs_usage        S_croak_xs_usage

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#if PERL_VERSION_LE(5, 21, 5)
#  define newXS_deffile(a,b) Perl_newXS(aTHX_ a,b,file)
#else
#  define newXS_deffile(a,b) Perl_newXS_deffile(aTHX_ a,b)
#endif

#line 189 "XS.c"

XS_EUPXS(XS_Data__RecordStore__XS_store_open); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Data__RecordStore__XS_store_open)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "directory");
    {
	char *	directory = (char *)SvPV_nolen(ST(0))
;
	RecordStore *	RETVAL;
#line 41 "XS.xs"
    RETVAL = open_store( directory );
#line 203 "XS.c"
	{
	    SV * RETVALSV;
	    RETVALSV = sv_newmortal();
	    sv_setref_pv(RETVALSV, "RecordStorePtr", (void*)RETVAL);
	    ST(0) = RETVALSV;
	}
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Data__RecordStore__XS_store_fetch); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Data__RecordStore__XS_store_fetch)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "store, rid");
    {
	RecordStore *	store;
	uint64_t    rid = (unsigned long long)SvUV(ST(1))
;
	char *	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "RecordStorePtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    store = INT2PTR(RecordStore *,tmp);
	}
	else
	    Perl_croak_nocontext("%s: %s is not of type %s",
			"Data::RecordStore::XS::store_fetch",
			"store", "RecordStorePtr")
;
#line 50 "XS.xs"
     RETVAL = fetch( store, rid );
#line 239 "XS.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Data__RecordStore__XS_store_stow); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Data__RecordStore__XS_store_stow)
{
    dVAR; dXSARGS;
    if (items != 4)
       croak_xs_usage(cv,  "store, data, rid, write_amount");
    {
	RecordStore *	store;
	char *	data = (char *)SvPV_nolen(ST(1))
;
	uint64_t    rid = (unsigned long long)SvUV(ST(2))
;
	uint64_t    write_amount = (unsigned long long)SvUV(ST(3))
;
	uint64_t	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "RecordStorePtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    store = INT2PTR(RecordStore *,tmp);
	}
	else
	    Perl_croak_nocontext("%s: %s is not of type %s",
			"Data::RecordStore::XS::store_stow",
			"store", "RecordStorePtr")
;
#line 61 "XS.xs"
     RETVAL = stow( store, data, rid, write_amount );
#line 274 "XS.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Data__RecordStore__XS_store_next_id); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Data__RecordStore__XS_store_next_id)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "store");
    {
	RecordStore *	store;
	uint64_t	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "RecordStorePtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    store = INT2PTR(RecordStore *,tmp);
	}
	else
	    Perl_croak_nocontext("%s: %s is not of type %s",
			"Data::RecordStore::XS::store_next_id",
			"store", "RecordStorePtr")
;
#line 70 "XS.xs"
     RETVAL = next_id( store );
#line 303 "XS.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Data__RecordStore__Silo__XS_silo_open); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Data__RecordStore__Silo__XS_silo_open)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "directory, size");
    {
	char *	directory = (char *)SvPV_nolen(ST(0))
;
	uint64_t    size = (unsigned long long)SvUV(ST(1))
;
	Silo *	RETVAL;
#line 82 "XS.xs"
    RETVAL = open_silo( directory, size );
#line 324 "XS.c"
	{
	    SV * RETVALSV;
	    RETVALSV = sv_newmortal();
	    sv_setref_pv(RETVALSV, "SiloPtr", (void*)RETVAL);
	    ST(0) = RETVALSV;
	}
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Data__RecordStore__Silo__XS_next_id_silo); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Data__RecordStore__Silo__XS_next_id_silo)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "silo");
    {
	Silo *	silo;
	uint64_t	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "SiloPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    silo = INT2PTR(Silo *,tmp);
	}
	else
	    Perl_croak_nocontext("%s: %s is not of type %s",
			"Data::RecordStore::Silo::XS::next_id_silo",
			"silo", "SiloPtr")
;
#line 90 "XS.xs"
     RETVAL = silo_next_id( silo );
#line 358 "XS.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Data__RecordStore__Silo__XS_put_record_silo); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Data__RecordStore__Silo__XS_put_record_silo)
{
    dVAR; dXSARGS;
    if (items != 4)
       croak_xs_usage(cv,  "silo, sid, data, write_size");
    {
	Silo *	silo;
	uint64_t    sid = (unsigned long long)SvUV(ST(1))
;
	char *	data = (char *)SvPV_nolen(ST(2))
;
	uint64_t    write_size = (unsigned long long)SvUV(ST(3))
;
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "SiloPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    silo = INT2PTR(Silo *,tmp);
	}
	else
	    Perl_croak_nocontext("%s: %s is not of type %s",
			"Data::RecordStore::Silo::XS::put_record_silo",
			"silo", "SiloPtr")
;
#line 101 "XS.xs"
     RETVAL = silo_put_record( silo, sid, data, write_size );
#line 393 "XS.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Data__RecordStore__Silo__XS_get_record_silo); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Data__RecordStore__Silo__XS_get_record_silo)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "silo, sid");
    {
	Silo *	silo;
	uint64_t    sid = (unsigned long long)SvUV(ST(1))
;
	char *	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "SiloPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    silo = INT2PTR(Silo *,tmp);
	}
	else
	    Perl_croak_nocontext("%s: %s is not of type %s",
			"Data::RecordStore::Silo::XS::get_record_silo",
			"silo", "SiloPtr")
;
#line 110 "XS.xs"
     RETVAL = silo_get_record( silo, sid );
#line 424 "XS.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Data__RecordStore__Silo__XS__silo_set_max_records); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Data__RecordStore__Silo__XS__silo_set_max_records)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "silo, recs");
    {
	Silo *	silo;
	int	recs = (int)SvIV(ST(1))
;
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "SiloPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    silo = INT2PTR(Silo *,tmp);
	}
	else
	    Perl_croak_nocontext("%s: %s is not of type %s",
			"Data::RecordStore::Silo::XS::_silo_set_max_records",
			"silo", "SiloPtr")
;
#line 120 "XS.xs"
    silo->file_max_records = recs;
    RETVAL = silo->file_max_records;
#line 456 "XS.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_Data__RecordStore__XS); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Data__RecordStore__XS)
{
#if PERL_VERSION_LE(5, 21, 5)
    dVAR; dXSARGS;
#else
    dVAR; dXSBOOTARGSXSAPIVERCHK;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(file);

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#if PERL_VERSION_LE(5, 21, 5)
    XS_VERSION_BOOTCHECK;
#  ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#  endif
#endif

        newXS_deffile("Data::RecordStore::XS::store_open", XS_Data__RecordStore__XS_store_open);
        newXS_deffile("Data::RecordStore::XS::store_fetch", XS_Data__RecordStore__XS_store_fetch);
        newXS_deffile("Data::RecordStore::XS::store_stow", XS_Data__RecordStore__XS_store_stow);
        newXS_deffile("Data::RecordStore::XS::store_next_id", XS_Data__RecordStore__XS_store_next_id);
        newXS_deffile("Data::RecordStore::Silo::XS::silo_open", XS_Data__RecordStore__Silo__XS_silo_open);
        newXS_deffile("Data::RecordStore::Silo::XS::next_id_silo", XS_Data__RecordStore__Silo__XS_next_id_silo);
        newXS_deffile("Data::RecordStore::Silo::XS::put_record_silo", XS_Data__RecordStore__Silo__XS_put_record_silo);
        newXS_deffile("Data::RecordStore::Silo::XS::get_record_silo", XS_Data__RecordStore__Silo__XS_get_record_silo);
        newXS_deffile("Data::RecordStore::Silo::XS::_silo_set_max_records", XS_Data__RecordStore__Silo__XS__silo_set_max_records);
#if PERL_VERSION_LE(5, 21, 5)
#  if PERL_VERSION_GE(5, 9, 0)
    if (PL_unitcheckav)
        call_list(PL_scopestack_ix, PL_unitcheckav);
#  endif
    XSRETURN_YES;
#else
    Perl_xs_boot_epilog(aTHX_ ax);
#endif
}

