---
abstract: 'Light-weight socket based resource locking manager.'
author:
  - unknown
build_requires:
  Module::Build: '0'
  Test::More: '0'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4218, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Lock-Server
provides:
  Lock::Server:
    file: lib/Lock/Server.pm
    version: '1.62'
  Lock::Server::Client:
    file: lib/Lock/Server.pm
    version: '1.62'
requires:
  perl: v5.9.4
resources:
  license: http://dev.perl.org/licenses/
version: '1.62'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
