---
abstract: 'Persistant Perl container objects in a directed graph of lazilly loaded nodes.'
author:
  - 'Eric Wolf        coyocanid@gmail.com'
build_requires:
  Module::Build: '0.4'
  Test::More: '0'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4214, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Yote
provides:
  Yote:
    file: lib/Yote.pm
    version: '1.31'
  Yote::Array:
    file: lib/Yote.pm
    version: '1.31'
  Yote::Hash:
    file: lib/Yote.pm
    version: '1.31'
  Yote::Obj:
    file: lib/Yote.pm
    version: '1.31'
  Yote::ObjStore:
    file: lib/Yote.pm
    version: '1.31'
  Yote::YoteDB:
    file: lib/Yote.pm
    version: '1.31'
requires:
  DB::DataStore: '1'
  Devel::Refcount: '0.1'
  JSON: '0'
  WeakRef: '0.01'
  perl: v5.12.0
resources:
  license: http://dev.perl.org/licenses/
version: '1.31'
x_serialization_backend: 'CPAN::Meta::YAML version 0.012'
